import { test, expect } from '@playwright/test';
import { fresh, KEY } from '../../src/progression';
test('typing, replacing, deleting and indenting preserve the caret mid-code',async({page})=>{
 const original='const name = "Ada";\nexport function Welcome() {\n  return <h1 className="welcome">Hello, {name}</h1>;\n}';
 const save=fresh();save.phase='exercise';save.settings.reducedMotion=true;save.settings.mute=true;save.answers['0-0']={code:original};
 await page.addInitScript(([key,value])=>{if(window===window.top&&!localStorage.getItem(key))localStorage.setItem(key,value);},[KEY,JSON.stringify(save)]);
 await page.goto('/');await page.getByRole('button',{name:'Use computer'}).click();
 const editor=page.getByRole('textbox',{name:'Your React code'});
 const saved=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).answers['0-0'].code,KEY);
 await page.locator('.cm-line').first().click();await editor.press('Home');
 for(let i=0;i<original.indexOf('Ada');i++)await editor.press('ArrowRight');
 await editor.pressSequentially('Dr. ',{delay:50});await expect.poll(saved).toBe(original.replace('Ada','Dr. Ada'));
 await editor.press('Backspace');await expect.poll(saved).toBe(original.replace('Ada','Dr.Ada'));
 for(let i=0;i<3;i++)await editor.press('Shift+ArrowLeft');
 await editor.pressSequentially('Captain ',{delay:40});await expect.poll(saved).toBe(original.replace('Ada','Captain Ada'));
 await page.getByRole('menuitem',{name:'Edit',exact:true}).click();await page.getByRole('menuitem',{name:'Undo Ctrl+Z'}).click();await expect.poll(saved).not.toBe(original.replace('Ada','Captain Ada'));
 await page.getByRole('menuitem',{name:'Edit',exact:true}).click();await page.getByRole('menuitem',{name:'Redo Ctrl+Y'}).click();await expect.poll(saved).toBe(original.replace('Ada','Captain Ada'));
 await page.locator('.cm-line').nth(2).click();await editor.press('Home');await editor.press('Tab');
 await expect.poll(saved).toBe(original.replace('Ada','Captain Ada').replace('  return','    return'));
 const final=await saved();await page.reload();await page.getByRole('button',{name:'Use computer'}).click();await expect(editor).toHaveText(final,{useInnerText:true});
});
